config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update] do
    member do
      get :participatings
      get :participateds
      get :message_lists
    end
  end  
  resources :team_informations, only: [:new, :create, :destroy, :edit, :update] 
  
  get 'team_informations/:id', to: 'team_informations#is_finished'
  post 'team_informations/:id', to: 'team_informations#is_finished'
  patch 'team_informations/:id', to: 'team_informations#is_finished'
  put 'team_informations/:id', to: 'team_informations#is_finished'
  
  resources :rooms, only: [:show, :create, :destroy]
  
  resources :messages, only: [:create]
end

app/models/team_information.rb
class TeamInformation < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 500 }
  validates :name, presence: true, length: { maximum: 30 }
  validates :region, presence: true, length: { maximum: 30 }
  validates :recruiting_people, presence: true, length: { maximum: 30 }
  
  
end

app/controllers/team_informations_controller.rb
class TeamInformationsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy,:edit,:update]
  def new
    @team_information = TeamInformation.new
  end

  def create
    @user = User.find(current_user.id)
    @team_information = current_user.team_informations.build(team_information_params)
    if @team_information.save
      flash[:success] = 'チームを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'チームに登録に失敗しました。'
      render :new
    end
  end

  def edit
    @team_information = TeamInformation.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    @team_information = TeamInformation.find(params[:id])
    
    if @team_information.update(team_information_params)
      flash[:success] = 'チーム情報は正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'チーム情報は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @team_information.destroy
    flash[:success] = 'チーム情報を削除しました。'
    redirect_back(fallback_location: root_path)
  end
 
 def is_finished
    @user = User.find(current_user.id)
    @team_information = TeamInformation.find(params[:id])
    if @team_information.update(is_finished: true)
      flash[:success] = '受付を終了しました'
      redirect_to @user
    end
 end
  
  private

  def team_information_params
    params.require(:team_information).permit(:content, :region, :recruiting_people, :name)
  end
  
  def correct_user
    @team_information = current_user.team_informations.find_by(id: params[:id])
    unless @team_information
      redirect_to root_url
    end
  end
end

app/views/team_informations/_team_informations.html.erb
<% team_informations.each do |team_information| %>
    <div class="border">
        <% if team_information.is_finished? %>
            <div class="alert alert-warning" role="alert">受付終了</div>
        <% end %>
        <p>チーム名：<%= team_information.name %></p>
        <p>地域：<%= team_information.region %></p>
        <p>募集人数：<%= team_information.recruiting_people %></p>
        <p>本文：<br> <%= safe_join(team_information.content.split("\n"),tag(:br)) %></p>
        <% if current_user == team_information.user %>
            <%= link_to 'チーム情報を編集', edit_team_information_path(team_information),class: 'btn btn-lg btn-secondary btn-sm' %>
            <%= link_to "削除", team_information, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% unless team_information.is_finished? %>
                <%= link_to "受付終了", team_information, method: :is_finished, data: { confirm: "You sure?" }, class: 'btn btn-warning btn-sm' %>
            <% end %>
        <% end %>
    </div>
<% end %>

<%= paginate team_informations %>

app/views/team_informations/_team_informations2.html.erb
<% team_informations.each do |team_information| %>
  <div>
    <%= link_to team_information.user.name, user_path(team_information.user) %> <span class="text-muted">posted at <%= team_information.created_at %></span>
  </div>
  <% if team_information.is_finished? %>
    <p><span class="badge badge-warning">受付終了</span></p>
  <% end %>
  <p>チーム名：<%= team_information.name %></p>
  <p>地域：<%= team_information.region %></p>
  <p>募集人数：<%= team_information.recruiting_people %></p>
<% end %>
<%= paginate team_informations %>

app/views/team_informations/create.html.erb
<h1>TeamInformations#create</h1>
<p>Find me in app/views/team_informations/create.html.erb</p>

app/views/team_informations/destroy.html.erb
<h1>TeamInformations#destroy</h1>
<p>Find me in app/views/team_informations/destroy.html.erb</p>

app/views/team_informations/edit.html.erb
<div class="text-center">
  <h1>チーム情報編集</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @team_information, local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, 'チーム名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
       <div class="form-group">
        <%= f.label :region, '地域' %>
        <%= f.text_field :region, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :recruiting_people, '募集人数' %>
        <%= f.text_field :recruiting_people, class: 'form-control' %>
      </div> 
      
      <div class="form-group">
        <%= f.label :content, '本文' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      <%= f.submit '編集', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/team_informations/new.html.erb
<div class="text-center">
  <h1>チーム情報登録</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @team_information, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'チーム名（必須）' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
       <div class="form-group">
        <%= f.label :region, '地域（必須）' %>
        <%= f.text_field :region, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :recruiting_people, '募集人数（必須）' %>
        <%= f.text_field :recruiting_people, class: 'form-control' %>
      </div> 
      
      <div class="form-group">
        <%= f.label :content, '本文（必須）' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/team_informations/update.html.erb
<h1>TeamInformations#update</h1>
<p>Find me in app/views/team_informations/update.html.erb</p>