config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update] do
    member do
      get :participatings
      get :participateds
      get :message_lists
    end
  end  
  resources :team_informations, only: [:new, :create, :destroy, :edit, :update] 
  
  get 'team_informations/:id', to: 'team_informations#is_finished'
  post 'team_informations/:id', to: 'team_informations#is_finished'
  patch 'team_informations/:id', to: 'team_informations#is_finished'
  put 'team_informations/:id', to: 'team_informations#is_finished'
  
  resources :rooms, only: [:show, :create, :destroy]
  
  resources :messages, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :age, presence: true, length: { maximum: 5 } 
  validates :baseball_experience, presence: true, length: { maximum: 50 }
  has_secure_password
  
  def is_finished?
      self.team_informations.include?(is_finished: 'true')
  end
  
  has_many :team_informations
  has_many :rooms, dependent: :destroy
  has_many :participatings, through: :rooms, source: :participate
  has_many :reverses_of_room, class_name: 'Room', foreign_key: 'participate_id'
  has_many :participateds, through: :reverses_of_room, source: :user
  has_many :messages, dependent: :destroy
  
  def participate(other_user)
    unless self == other_user
      self.rooms.find_or_create_by(participate_id: other_user.id)
    end
  end
  
  
  def participate?(other_user)
    self.participatings.include?(other_user)
  end
  
  def feed_messages
    Message.where(user_id: self.participated_ids + [self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in,only: [:show, :edit, :message_lists]
  before_action :correct_user, only: [:edit, :update, :message_lists]
  
  def show
    @user = User.find(params[:id])
    @team_informations = @user.team_informations.order(id: :desc).page(params[:page]).per(10)
    @rooms = @user.rooms.order(id: :desc).page(params[:page]).per(3)
    @participate_user = Room.where(participate_id: current_user)
    @participate_room = @participate_user.order(id: :desc).page(params[:page]).per(3)
  end
  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'ユーザー情報は正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報は更新されませんでした'
      render :edit
    end
  end
  
  def message_lists
    @message_lists = current_user.feed_messages.order(id: :desc).page(params[:page]).per(5)
  end
  
  
private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :baseball_experience)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
  
end

app/views/users/_message_lists.html.erb
<div class = mb-4>
    <% messages.each do |message| %>
        <ul>
            <li><%= message.user.name %> : <%= message.body %>　　　　書き込んだ時間： <%= message.created_at %></span></li>
            <div>
                <%= link_to "ルームに遷移する", room_path(message.room) %>
            </div>
        </ul>
    <% end %>
</div>

<%= paginate messages %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>ユーザー情報編集</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
       <div class="form-group">
        <%= f.label :age, '年齢' %>
        <%= f.text_field :age, class: 'form-control' %>歳
      </div>

      <div class="form-group">
        <%= f.label :baseball_experience, '野球経験' %>
        <%= f.text_field :baseball_experience, class: 'form-control' %>（ありorなし）
      </div> 
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
  <div class="offset-sm-8 col-sm-3 offset-sm-1 text-right pt-5 mt-5" >
      <%= link_to 'ユーザーページに戻る', @user %>
  </div>
  
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/message_lists.erb
<h1><メッセージリスト></h1>
<%= render 'users/message_lists', messages: @message_lists,messages1: @message_lists1 %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>会員登録</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前(必須）' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス（必須）' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード（必須）' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認（必須）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
       <div class="form-group">
        <%= f.label :age, '年齢（必須）' %>
        <%= f.text_field :age, class: 'form-control' %>歳
      </div>

      <div class="form-group">
        <%= f.label :baseball_experience, '野球経験（必須）' %>
        <%= f.text_field :baseball_experience, class: 'form-control' %>（ありorなし）
      </div> 
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user == @user %>
    <div class="row">
        <div class="col-sm-4">
             <div class="text-center">
                 <h1>ユーザー情報</h1>
             </div>
             <table class="table">
                 <tr>
                     <td>名前:</td>
                     <td><%= @user.name %></td>
                 </tr>    
                 <tr>
                     <td>年齢:</td>
                     <td><%= @user.age %></td>
                 </tr>    
                  <tr>
                     <td>野球経験:</td>
                     <td><%= @user.baseball_experience %></td>
                 </tr> 
             </table>
             <div class="text-right mb-2">    
                 <%= link_to 'ユーザー情報を編集', edit_user_path, class: 'btn btn-lg btn-secondary' %>
             </div> 
             <div>
                 <%= render 'rooms/rooms', rooms: @rooms %>
                 <%= render 'rooms/rooms2', rooms: @participate_room %>
             </div>
             <div class="text-right mb-2">
                 <%= link_to 'メッセージ一覧', message_lists_user_path, class: 'btn btn-lg btn-primary' %>
             </div>
        </div>
        <div class="col-sm-8">
            <h1 class="text-center">チーム情報</h1>
            <%= render 'team_informations/team_informations', team_informations: @team_informations %>
        <div class="text-right mb-2">    
            <%= link_to 'チームを登録する', new_team_information_path, class: 'btn btn-lg btn-success' %>
        </div>
        </div>
        
      
    </div>
<% else %>
    <div class="row">
        <div class="col-sm-4">
             <div class="text-center">
                 <h1>ユーザー情報</h1>
             </div>
             <table class="table">
                 <tr>
                     <td>名前:</td>
                     <td><%= @user.name %></td>
                 </tr>    
                 <tr>
                     <td>年齢:</td>
                     <td><%= @user.age %></td>
                 </tr>    
                  <tr>
                     <td>野球経験:</td>
                     <td><%= @user.baseball_experience %></td>
                 </tr> 
             </table>
             <%= render 'rooms/participate_button', user: @user %>
        </div>
        <div class="col-sm-8">
            <h1 class="text-center">チーム情報</h1>
            <%= render 'team_informations/team_informations', team_informations: @team_informations %>
        </div>
      
    </div>

<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>