config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update] do
    member do
      get :participatings
      get :participateds
      get :message_lists
    end
  end  
  resources :team_informations, only: [:new, :create, :destroy, :edit, :update] 
  
  get 'team_informations/:id', to: 'team_informations#is_finished'
  post 'team_informations/:id', to: 'team_informations#is_finished'
  patch 'team_informations/:id', to: 'team_informations#is_finished'
  put 'team_informations/:id', to: 'team_informations#is_finished'
  
  resources :rooms, only: [:show, :create, :destroy]
  
  resources :messages, only: [:create]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @team_informations = TeamInformation.order(id: :desc).page(params[:page]).per(5)
  end
end

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>草野球メンバー募集</h1>
    </div>
  </div>
  <div class = "text-center">
      <h3 class = "border-bottom pb-3 mb-3">こちらは、京都の草野球チームの選手を募集するサイトです</h3>
      <h3 class = "border-bottom pb-3 mb-3">自由に募集してメンバーを集めてください</h3>
  </div>
  <div class="border">
    <h2>チーム情報</h2>
    <%= render 'team_informations/team_informations2', team_informations: @team_informations %>
    
  </div>
<% else %>
  <div class="offset-md-8 col-md-4 pb-4">
      <%= link_to '会員登録', signup_path, class: 'btn btn-lg btn-primary' %>
      <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-primary' %>
  </div>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>草野球メンバー募集</h1>
    </div>
  </div>
  <div class = 'text-center'>
      <h3>こちらは、京都の草野球チームの選手を募集するサイトです
      <br><br>自由に募集してメンバーを集めてください
  </div>
<% end %>