config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update] do
    member do
      get :participatings
      get :participateds
      get :message_lists
    end
  end  
  resources :team_informations, only: [:new, :create, :destroy, :edit, :update] 
  
  get 'team_informations/:id', to: 'team_informations#is_finished'
  post 'team_informations/:id', to: 'team_informations#is_finished'
  patch 'team_informations/:id', to: 'team_informations#is_finished'
  put 'team_informations/:id', to: 'team_informations#is_finished'
  
  resources :rooms, only: [:show, :create, :destroy]
  
  resources :messages, only: [:create]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
  <header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a href="/" class="navbar-brand">Rec_baseball</a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="nav-bar">
          <ul class="navbar-nav">
              <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">ユーザー</a>
                  <ul class="dropdown-menu dropdown-menu-right">
                      <li class="dropdown-item"><%= link_to 'ユーザー情報', user_path(current_user) %></li>
                      <li class="dropdown-item"><%= link_to 'メッセージ一覧', message_lists_user_path(current_user) %></li>
                      <li class="dropdown-divider"></li>
                      <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
                  </ul>
              </li>
          </ul>
      </div>
    </nav>
  </header>
<% else %>
  <header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a href="/" class="navbar-brand">Rec_baseball</a>
    </nav>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RecBaseball</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>